org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

# Uncomment and set the path below if you are building on an ARM64 Linux system 
# and facing AAPT2 errors (e.g. "Syntax error: Unterminated quoted string").
# Google does not officially provide ARM64 Linux AAPT2 via Maven, 
# so you can install it via `sudo apt install aapt` and point to it:
# android.aapt2FromMavenOverride=/usr/bin/aapt2

